### ISSUE TITLE
Error: ANDROID_HOME is not set and "android" command not in your PATH.

### ISSUE THREAD

**Issue by hirokihara** [GrayBullet/generator-graybullet-cordova#10]
Cannot create project with windows.Throw error, Error: ANDROID_HOME is not set and "android" command not in your PATH. 

```
C:\Users\Owner\Documents\graybullet>yo graybullet-cordova

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |   Welcome to the Apache  |
   `---------´   |    Cordova generator!    |
    ( _´U`_ )    '--------------------------'
    /___A___\
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? What is the name of Apache Cordova App? HelloCordova
? What is the ID of Apache Cordova App? io.cordova.hellocordova
? What app of the platform to be created? android

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Command failed:
C:\Users\Owner\.cordova\lib\npm_cache\cordova-android\3.6.4\package\bin\node_modules\q\q.js:126
                    throw e;
                          ^
Error: ANDROID_HOME is not set and "android" command not in your PATH. You must fulfill at least one of these conditions.
    at C:\Users\Owner\.cordova\lib\npm_cache\cordova-android\3.6.4\package\bin\lib\check_reqs.js:159:19
    at _fulfilled (C:\Users\Owner\.cordova\lib\npm_cache\cordova-android\3.6.4\package\bin\node_modules\q\q.js:798:54)
    at self.promiseDispatch.done (C:\Users\Owner\.cordova\lib\npm_cache\cordova-android\3.6.4\package\bin\node_modules\q\q.js:827:30)
    at Promise.promise.promiseDispatch (C:\Users\Owner\.cordova\lib\npm_cache\cordova-android\3.6.4\package\bin\node_modules\q\q.js:760:13)
    at C:\Users\Owner\.cordova\lib\npm_cache\cordova-android\3.6.4\package\bin\node_modules\q\q.js:821:14
    at flush (C:\Users\Owner\.cordova\lib\npm_cache\cordova-android\3.6.4\package\bin\node_modules\q\q.js:108:17)
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3

    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)

C:\Users\Owner\Documents\graybullet>
```

**Comment by rbecheras** [comment]
You have to download ans install the Android SDK on android.com and configure your home PATH before trying to create a project.

It is a "dependency"

**Comment by rbecheras** [comment]
I guess this issue can be closed.

**Comment by hirokihara** [comment]
Thanks rbecheras, I will close this issue.
