### ISSUE TITLE
Cannot create project Throw error, Error: Command failed: cordova platform add ios android

### ISSUE THREAD

**Issue by hirokihara** [GrayBullet/generator-graybullet-cordova#26]
Cannot create project Throw error, Error: Command failed: cordova platform add ios android

environment

```
wacca:graybullet-cordova owner$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.2
BuildVersion:	14C109
wacca:graybullet-cordova owner$ node --version
v0.12.0
wacca:graybullet-cordova owner$ npm -g list --depth=0
/usr/local/lib
├── bower@1.3.12
├── cordova@4.3.0
├── generator-graybullet-cordova@0.2.0
├── generator-jasmine@0.1.3
├── generator-mocha@0.1.6
├── generator-webapp@0.5.1
├── grunt-cli@0.1.13
├── jscs@1.11.3
├── jsdoc@3.3.0-beta1
├── jshint@2.6.3
├── npm@2.6.1
└── yo@1.4.5

wacca:graybullet-cordova owner$ android list target
Unable to find a $JAVA_HOME at "/usr/", continuing with system-provided Java...
Unable to find a $JAVA_HOME at "/usr/", continuing with system-provided Java...
Unable to find a $JAVA_HOME at "/usr/", continuing with system-provided Java...
Available Android targets:
----------
id: 1 or "android-17"
     Name: Android 4.2.2
     Type: Platform
     API level: 17
     Revision: 3
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : default/armeabi-v7a, default/x86
----------
id: 2 or "android-19"
     Name: Android 4.4.2
     Type: Platform
     API level: 19
     Revision: 4
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : default/armeabi-v7a, default/x86
----------
id: 3 or "android-21"
     Name: Android 5.0.1
     Type: Platform
     API level: 21
     Revision: 2
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : default/armeabi-v7a, default/x86, default/x86_64
wacca:graybullet-cordova owner$ 
```

log

```
wacca:graybullet-cordova owner$ yo graybullet-cordova

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |   Welcome to the Apache  |
   `---------´   |    Cordova generator!    |
    ( _´U`_ )    '--------------------------'
    /___A___\    
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? What is the name of Apache Cordova App? HelloCordova
? What is the ID of Apache Cordova App? io.cordova.hellocordova
? What app of the platform to be created? ios, android
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Command failed: cordova platform add ios android
npm http GET https://registry.npmjs.org/cordova-ios/3.8.0
TypeError: Request path contains unescaped characters.
    at new ClientRequest (_http_client.js:73:11)
    at TunnelingAgent.exports.request (http.js:49:10)
    at TunnelingAgent.createSocket (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:117:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:184:41)
    at TunnelingAgent.addRequest (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:80:8)
    at new ClientRequest (_http_client.js:154:16)
    at Object.exports.request (http.js:49:10)
    at Object.exports.request (https.js:136:15)
    at Request.start (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:594:30)
    at Request.end (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:1186:28)

    at ChildProcess.exithandler (child_process.js:744:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)
wacca:graybullet-cordova owner$ 
```

**Comment by masakura** [comment]
Thanks! @hirokihara 

This problem was cordova@4.3.0 bug inside authenticate proxy. [[CB-8611]](https://issues.apache.org/jira/browse/CB-8611)

Please try do any.

- Downgrade to node@0.10.36
- Downgrade to cordova@4.2.0
- Don't use proxy

**Comment by masakura** [comment]
It operate correctly out of proxy. Close.
