### ISSUE TITLE
Cannot create project on Windows 7

### ISSUE THREAD

**Issue by hirokihara** [GrayBullet/generator-graybullet-cordova#33]
Cannot create project on Windows 7

```
C:\Users\RIA\work\graybullet>yo graybullet-cordova

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |   Welcome to the Apache  |
   `---------´   |    Cordova generator!    |
    ( _´U`_ )    '--------------------------'
    /___A___\
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? What is the name of Apache Cordova App? HelloCordova
? What is the ID of Apache Cordova App? io.cordova.hellocordova
? What app of the platform to be created? android
? Are you sure you want to add any plugins? org.apache.cordova.device


fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\C:\Users\RIA\AppData\Roaming\nvm\v4.3.1\node_modules\generator-webapp\package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.module.exports.getVersion (C:\Users\RIA\AppData\Roaming\nvm\v4.3.1\node_modules\generator-graybullet-cordova\app\generatorInfo.js:39:37)
    at Object.module.exports.makeInfo (C:\Users\RIA\AppData\Roaming\nvm\v4.3.1\node_modules\generator-graybullet-cordova\app\generatorInfo.js:20:25)
    at Object.<anonymous> (C:\Users\RIA\AppData\Roaming\nvm\v4.3.1\node_modules\generator-graybullet-cordova\app\generatorInfo.js:12:21)
    at Environment.resolver.lookup (C:\Users\RIA\AppData\Roaming\nvm\v4.3.1\node_modules\generator-graybullet-cordova\node_modules\yeoman-environment\lib\resolver.js:50:12)
    at Object.module.exports.getInfo (C:\Users\RIA\AppData\Roaming\nvm\v4.3.1\node_modules\generator-graybullet-cordova\app\generatorInfo.js:14:17)
    at GeneratorUtil.getFilterFactory (C:\Users\RIA\AppData\Roaming\nvm\v4.3.1\node_modules\generator-graybullet-cordova\app\generatorUtil.js:39:33)
    at yeoman.generators.Base.extend.prompting.getFilter (C:\Users\RIA\AppData\Roaming\nvm\v4.3.1\node_modules\generator-graybullet-cordova\app\index.js:208:12)
```

環境

```
C:\Users\RIA\work\graybullet>node -v
v4.3.1

C:\Users\RIA\work\graybullet>npm -v
3.7.3

C:\Users\RIA\work\graybullet>npm list -g --depth 0
C:\Program Files\nodejs
+-- bower@1.7.7
+-- cordova@5.4.1
+-- generator-angular@0.14.0
+-- generator-backbone@0.4.2
+-- generator-backbone-mocha@0.1.1
+-- generator-graybullet-cordova@0.4.0
+-- generator-jasmine@0.2.2
+-- generator-karma@1.0.1
+-- generator-mocha@0.3.0
+-- generator-webapp@1.1.0
+-- grunt-cli@0.1.13
+-- jscs@2.10.1
+-- jsdoc@3.4.0
+-- jshint@2.9.1
+-- npm@3.7.3
`-- yo@1.6.0


C:\Users\RIA\work\graybullet>
```

**Comment by masakura** [comment]
Fix bug v0.4.1.

Run `npm upgrade -g generator-graybullet-cordova`!
